# Generated by Django 3.1.5 on 2022-04-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_auto_20220404_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
