# Generated by Django 3.1.5 on 2022-05-03 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ugc', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='page_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
